### ISSUE TITLE
tpot does not create memory dir and gives spurious error

### ISSUE THREAD

**Issue by cottrell** [EpistasisLab/tpot#837] opened 2019-02-20 08:58 UTC
I get this error: RuntimeError: A pipeline has not yet been optimized. Please call fit() first.

if I don't create the memory dir first. I think fix is easy in base.py but probably needs an opinion on correct behaviour.

**Comment by weixuanfu** [comment] 2019-02-20 10:13
Hmm, TPOT should raise a ValueError when the memory folder does not exist. Was the error raised in this case? Could you please provide more details about this issue, like codes for reproducing it?

**Comment by cottrell** [comment] 2019-03-10 20:03
Here is code

```
In [22]: t = tpot.TPOTClassifier(memory='asdf')                                                                                                                                                                    

In [23]: t.fit(np.random.randn(100, 5), np.random.rand(100) > 0.5)                                                                                                                                                 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/dev/tpot/tpot/base.py in fit(self, features, target, sample_weight, groups)
    647             with warnings.catch_warnings():
--> 648                 self._setup_memory()
    649                 warnings.simplefilter('ignore')

~/dev/tpot/tpot/base.py in _setup_memory(self)
    708                     raise ValueError(
--> 709                         'Could not find directory for memory caching: {}'.format(self.memory)
    710                     )

ValueError: Could not find directory for memory caching: asdf

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-23-1844720facf9> in <module>
----> 1 t.fit(np.random.randn(100, 5), np.random.rand(100) > 0.5)

~/dev/tpot/tpot/base.py in fit(self, features, target, sample_weight, groups)
    691                     # raise the exception if it's our last attempt
    692                     if attempt == (attempts - 1):
--> 693                         raise e
    694             return self
    695 

~/dev/tpot/tpot/base.py in fit(self, features, target, sample_weight, groups)
    682                         self._pbar.close()
    683 
--> 684                     self._update_top_pipeline()
    685                     self._summary_of_best_pipeline(features, target)
    686                     # Delete the temporary cache before exiting

~/dev/tpot/tpot/base.py in _update_top_pipeline(self)
    756             # If user passes CTRL+C in initial generation, self._pareto_front (halloffame) shoule be not updated yet.
    757             # need raise RuntimeError because no pipeline has been optimized
--> 758             raise RuntimeError('A pipeline has not yet been optimized. Please call fit() first.')
    759 
    760     def _summary_of_best_pipeline(self, features, target):

RuntimeError: A pipeline has not yet been optimized. Please call fit() first.

```

**Comment by weixuanfu** [comment] 2019-03-11 11:35
`ValueError: Could not find directory for memory caching: asdf`

Besed on the error message above, the issue is caused by the wrong `memory` parameter. It should be a valid path of directory.

**Comment by cottrell** [comment] 2019-03-11 15:09
Yes, that is the bug. It should create the dir I think not error.

**Comment by weixuanfu** [comment] 2019-04-12 14:49
I close this issue because it is fixed in master branch. Please feel free to reopen it if there is other related issues.

**Closed as completed by weixuanfu** 2019-04-12 14:49 UTC
Labels: question
