### ISSUE TITLE
How to use tpot for logistic regression

### ISSUE THREAD

**Issue by pannalal** [EpistasisLab/tpot#618] opened 2017-11-08 05:41 UTC
This is a super piece of code for Data Scientists. I have used it for classification and regression with very good result.

I just want to know whether we can use tpot for logistic regression?

**Comment by weixuanfu** [comment] 2017-11-08 17:54
Do you mean using the GP optimization in TPOT for tuning parameters of logistic regression? If so there is hacky way for it:

One of my dev branch of TPOT called [noCDF_noStacking](https://github.com/weixuanfu/tpot/tree/noCDF_noStacking) has a option named `fixed_length`, which can disable `CombineDFs` if `fixed_length` is not None (e.g. `TPOTClassifier(fixed_length=1)`) and generate pipeline with fixed number of operators (e.g. `fixed_length=1` means only 1 operator). 

**Note: this dev branch is not fully tested yet**. 

You may install this branch in your test environment via the command below:

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@noCDF_noStacking
```

Then, you need use [a custom configuration](http://rhiever.github.io/tpot/using/#customizing-tpots-operators-and-parameters) with only one operator in this dictionary as the demo below:

```python
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

tpot_config = {
    'sklearn.linear_model.LogisticRegression': {
        'penalty': ["l1", "l2"],
        'C': [1e-4, 1e-3, 1e-2, 1e-1, 0.5, 1., 5., 10., 15., 20., 25.],
        'dual': [True, False]
    }
}

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2, 
                                 fixed_length=1, config_dict=tpot_config)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
```

**Comment by rhiever** [comment] 2017-11-08 19:11
Can you please clarify what you mean by this?

>I just want to know whether we can use tpot for logistic regression?

Logistic regression is a classification method and is included in the `TPOTClassifier` default configuration.

**Comment by pannalal** [comment] 2017-11-09 09:45
Sorry, I wanted to know whether I can use tpot for binary logistic. I have written logistic regression by mistake.

**Comment by rhiever** [comment] 2017-11-09 22:20
OK. Did @weixuanfu's answer above address your question?

**Comment by weixuanfu** [comment] 2017-11-29 15:54
I closed this issue since there is no answer in a while. Please feel free to re-open the issue (or comment further) if you have any more questions

**Closed as completed by weixuanfu** 2017-11-29 15:54 UTC
Labels: question
