### ISSUE TITLE
sklearn/preprocessing/_function_transformer.py:98: FutureWarning: The default validate=True will be replaced by validate=False in 0.22

### ISSUE THREAD

**Issue by fcoppey** [EpistasisLab/tpot#877] opened 2019-06-03 19:10 UTC
Hello,

when I predict my test_set I get endless output of that :
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:98: FutureWarning: The default validate=True will be replaced by validate=False in 0.22

any idea what to modify to make this go away?

thank you

**Comment by fcoppey** [comment] 2019-06-03 19:15
same problem with XGBoost :
WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

something to change here too?

**Comment by weixuanfu** [comment] 2019-06-03 19:26
> Hello,
> 
> when I predict my test_set I get endless output of that :
> /usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:98: FutureWarning: The default validate=True will be replaced by validate=False in 0.22
> 
> any idea what to modify to make this go away?
> 
> thank you


It seems FutureWarning message from the latest version of scikit-learn (0.21), we will update TPOT for fixing incompatibility issue in the next version of TPOT and should drop the supports of python 2.7 as scikit-learn 0.21 does. 


> same problem with XGBoost :
> WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
> 
> something to change here too?

This seems from the API changes from [latest version of xgboost](https://github.com/dmlc/xgboost/releases). I am not sure how this warning message is triggered since TPOT does not set `reg:linear`. Maybe it is a bug in this version of xgboost. We will try to find a workaround for it.

**Comment by fcoppey** [comment] 2019-06-03 19:30
thank you! awesome work that you do guys! I wish I could help but I'm unfortunately not so useful with my knowledge yet hehe. maybe later...

**Comment by shenglinqian** [comment] 2019-07-01 16:31
got the same problem with XGBoost
WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror
Anyone know how to figure it out?Thanks

**Comment by thunfischtoast** [comment] 2019-07-11 12:41
@shenglinqian @fcoppey you can prevent the deprecation warning by adding the following line to the config dictionary under the key ``xgboost.XGBRegressor``:

`` 'objective': ['reg:squarederror'] ``

If you don't have a dictionary yet just copy the default one from https://epistasislab.github.io/tpot/using/#built-in-tpot-configurations.

See https://github.com/EpistasisLab/tpot/pull/887/files for how it should look like.

**Comment by weixuanfu** [comment] 2019-07-17 13:07
The issue was fixed (#887 Thanks @thunfischtoast ) in the latest version of TPOT so I closed it. Please feel free to reopen if there is another issue.

**Closed as completed by weixuanfu** 2019-07-17 13:07 UTC
Labels: enhancement, question
