### ISSUE TITLE
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23

### ISSUE THREAD

**Issue by neffmallon** [EpistasisLab/tpot#869] opened 2019-05-22 14:04 UTC
On import, scikit-learn throws a deprecation warning, suggesting that joblib should be installed directly.

> Python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.

Joblib should be added to requirements.txt and TPOT should be refactored to refer to the joblib package where appropriate.

**Comment by weixuanfu** [comment] 2019-05-22 14:12
The issue is fixed in PR #867 and it was merged to development branch. It will be fixed into next version of TPOT.
BTW, because scikit-learn 0.21 only supports python 3, we may drop python 2 supports in near future due to too many api changes in the future version of scikit-learn.

**Closed as completed** 2019-05-30 12:49 UTC
