### ISSUE TITLE
TPOT Regressor not recognizing training data

### ISSUE THREAD

**Issue by ShaanKohli** [EpistasisLab/tpot#1068] opened 2020-05-15 17:59 UTC
When attempting to run the TPOTRegressor example from the TPOT documentation, it seems not to be running. I have tried looking into the source code and trying with different data but it seems like a consistent issue. I am not using a conda environment but google colab.

## Code

from tpot import TPOTRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

housing = load_boston()
X_train, X_test, y_train, y_test = train_test_split(housing.data, housing.target,train_size=0.75, test_size=0.25, random_state=42)
tpot = TPOTRegressor(generations=5, population_size=50, verbosity=2, random_state=42)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

## Error

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-6fb4b1fa5f6f> in <module>()
      X_train, X_test, y_train, y_test = train_test_split(housing.data, housing.target,train_size=0.75, test_size=0.25, random_state=42)
      tpot = TPOTRegressor(generations=5, population_size=50, verbosity=2, random_state=42)
----> tpot.fit(X_train, y_train)
      print(tpot.score(X_test, y_test))

/usr/local/lib/python3.6/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
             features, target = self._check_dataset(features, target, sample_weight)
-->          self._init_pretest(features, target)
   
           # Randomly collect a subsample of training samples for pipeline optimization process.

/usr/local/lib/python3.6/dist-packages/tpot/tpot.py in _init_pretest(self, features, target)
     
              """
--->         self.pretest_X, _, self.pretest_y, _ = train_test_split(X, y, random_state=self.random_state,
                                                                 test_size=None, train_size=min(50,int(0.9*features.shape[0])))

NameError: name 'X' is not defined

<img width="1158" alt="TpotRegressorError" src="https://user-images.githubusercontent.com/60670209/82081274-04fa1780-96b4-11ea-9294-52f51d23c195.png">

https://colab.research.google.com/drive/1xnxMps3x4XQDIwCycl1VQs5oq2ZFv4J5?usp=sharing

**Comment by weixuanfu** [comment] 2020-05-15 21:17
This is a bug in v0.11.2 and was fixed in v0.11.3a0. (See #1067)

Please try this version instead for now.

We will release a minor version after some checks next week.

**Comment by weixuanfu** [comment] 2020-05-21 13:25
The issue is fixed in v0.11.3

**Closed as completed by weixuanfu** 2020-05-21 13:25 UTC
Labels: bug
