### ISSUE TITLE
tpot 0.11.5 not printing result for each generation anymore

### ISSUE THREAD

**Issue by fcoppey** [EpistasisLab/tpot#1082] opened 2020-06-12 13:56 UTC
I can rapidly see the generation result then it is overwritten by the progress bar...
Am I the only one?

**Comment by weixuanfu** [comment] 2020-06-12 15:06
I found this issue when using ipython and I did not find this issue when using jupyter notebook. I pushed a path to development branch to fix the issue and we will release a new minor release with the patch.

You may try the dev branch via the command below:

```shell
pip install --upgrade --no-deps --force-reinstall git+https://github.com/EpistasisLab/tpot.git@development
```

**Comment by fcoppey** [comment] 2020-10-16 10:37
still not in release?

**Comment by weixuanfu** [comment] 2020-10-16 13:02
@fcoppey not yet, we will release it later this Month.

**Comment by weixuanfu** [comment] 2020-10-26 15:12
The issue is fixed in v0.11.6.

**Closed as completed by weixuanfu** 2020-10-26 15:12 UTC
Labels: bug
